/*
 * Copyright (c) 2026 Edgar Bernardi Righi <edgar.righi@lsitec.org.br>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_PUPPY_V2_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_PUPPY_V2_H_

#define PUPPY_UDMA_CLK_UART0	0x0
#define PUPPY_UDMA_CLK_SPI0	0x1
#define PUPPY_UDMA_CLK_SPI1	0x2
#define PUPPY_UDMA_CLK_I2C0	0x3
#define PUPPY_UDMA_CLK_I2C1	0x4
#define PUPPY_UDMA_CLK_SDIO	0x5
#define PUPPY_UDMA_CLK_I2S	0x6
#define PUPPY_UDMA_CLK_CAM	0x7
#define PUPPY_UDMA_CLK_UART1	0x8
#define PUPPY_UDMA_CLK_FILTER	0x9

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_PUPPY_V2_H_ */
