/*
 * Copyright (c) 2026 Edgar Bernardi Righi
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_PUPPY_V2_EVTC_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_PUPPY_V2_EVTC_H_

/* Puppy V2 Event Interrupt Controller (evtc) */

#include <zephyr/dt-bindings/dt-util.h>

/* Event source */

#define PUPPY_EVTC_SRC_UART0	0x0
#define PUPPY_EVTC_SRC_SPI0	0x1
#define PUPPY_EVTC_SRC_SPI1	0x2
#define PUPPY_EVTC_SRC_I2C0	0x3
#define PUPPY_EVTC_SRC_I2C1	0x4
#define PUPPY_EVTC_SRC_SDIO	0x5
#define PUPPY_EVTC_SRC_I2S	0x6
#define PUPPY_EVTC_SRC_CAM	0x7
#define PUPPY_EVTC_SRC_UART1	0x8
#define PUPPY_EVTC_SRC_FILTER	0x9

/* Event lines */

#define PUPPY_EVTC_L0(_src)	((_src) * 0x4 + 0x0)
#define PUPPY_EVTC_L1(_src)	((_src) * 0x4 + 0x1)
#define PUPPY_EVTC_L2(_src)	((_src) * 0x4 + 0x2)
#define PUPPY_EVTC_L3(_src)	((_src) * 0x4 + 0x3)

/* Event numbers */

/* UART0 */
#define PUPPY_EVTC_UART0_RX_IRQ		PUPPY_EVTC_L0(PUPPY_EVTC_SRC_UART0)
#define PUPPY_EVTC_UART0_TX_IRQ		PUPPY_EVTC_L1(PUPPY_EVTC_SRC_UART0)
#define PUPPY_EVTC_UART0_EOT_IRQ	PUPPY_EVTC_L2(PUPPY_EVTC_SRC_UART0)
#define PUPPY_EVTC_UART0_RX_DAT_IRQ	PUPPY_EVTC_L3(PUPPY_EVTC_SRC_UART0)
/* UART1 */
#define PUPPY_EVTC_UART1_RX_IRQ		PUPPY_EVTC_L0(PUPPY_EVTC_SRC_UART1)
#define PUPPY_EVTC_UART1_TX_IRQ		PUPPY_EVTC_L1(PUPPY_EVTC_SRC_UART1)
#define PUPPY_EVTC_UART1_EOT_IRQ	PUPPY_EVTC_L2(PUPPY_EVTC_SRC_UART1)
#define PUPPY_EVTC_UART1_RX_DAT_IRQ	PUPPY_EVTC_L3(PUPPY_EVTC_SRC_UART1)
/* SPI0 */
#define PUPPY_EVTC_SPI0_RX_IRQ		PUPPY_EVTC_L0(PUPPY_EVTC_SRC_SPI0)
#define PUPPY_EVTC_SPI0_TX_IRQ		PUPPY_EVTC_L1(PUPPY_EVTC_SRC_SPI0)
#define PUPPY_EVTC_SPI0_CMD_IRQ		PUPPY_EVTC_L2(PUPPY_EVTC_SRC_SPI0)
#define PUPPY_EVTC_SPI0_EOT_IRQ		PUPPY_EVTC_L3(PUPPY_EVTC_SRC_SPI0)
/* SPI1 */
#define PUPPY_EVTC_SPI1_RX_IRQ		PUPPY_EVTC_L0(PUPPY_EVTC_SRC_SPI1)
#define PUPPY_EVTC_SPI1_TX_IRQ		PUPPY_EVTC_L1(PUPPY_EVTC_SRC_SPI1)
#define PUPPY_EVTC_SPI1_CMD_IRQ		PUPPY_EVTC_L2(PUPPY_EVTC_SRC_SPI1)
#define PUPPY_EVTC_SPI1_EOT_IRQ		PUPPY_EVTC_L3(PUPPY_EVTC_SRC_SPI1)
/* I2C0 */
#define PUPPY_EVTC_I2C0_RX_IRQ		PUPPY_EVTC_L0(PUPPY_EVTC_SRC_I2C0)
#define PUPPY_EVTC_I2C0_TX_IRQ		PUPPY_EVTC_L1(PUPPY_EVTC_SRC_I2C0)
#define PUPPY_EVTC_I2C0_CMD_IRQ		PUPPY_EVTC_L2(PUPPY_EVTC_SRC_I2C0)
#define PUPPY_EVTC_I2C0_EOT_IRQ		PUPPY_EVTC_L3(PUPPY_EVTC_SRC_I2C0)
/* I2C1 */
#define PUPPY_EVTC_I2C1_RX_IRQ		PUPPY_EVTC_L0(PUPPY_EVTC_SRC_I2C1)
#define PUPPY_EVTC_I2C1_TX_IRQ		PUPPY_EVTC_L1(PUPPY_EVTC_SRC_I2C1)
#define PUPPY_EVTC_I2C1_CMD_IRQ		PUPPY_EVTC_L2(PUPPY_EVTC_SRC_I2C1)
#define PUPPY_EVTC_I2C1_EOT_IRQ		PUPPY_EVTC_L3(PUPPY_EVTC_SRC_I2C1)
/* SDIO */
#define PUPPY_EVTC_SDIO_RX_IRQ		PUPPY_EVTC_L0(PUPPY_EVTC_SRC_SDIO)
#define PUPPY_EVTC_SDIO_TX_IRQ		PUPPY_EVTC_L1(PUPPY_EVTC_SRC_SDIO)
#define PUPPY_EVTC_SDIO_CMD_IRQ		PUPPY_EVTC_L2(PUPPY_EVTC_SRC_SDIO)
#define PUPPY_EVTC_SDIO_EOT_IRQ		PUPPY_EVTC_L3(PUPPY_EVTC_SRC_SDIO)
/* I2S */
#define PUPPY_EVTC_I2S_RX_IRQ		PUPPY_EVTC_L0(PUPPY_EVTC_SRC_I2S)
#define PUPPY_EVTC_I2S_TX_IRQ		PUPPY_EVTC_L1(PUPPY_EVTC_SRC_I2S)
/* CAM */
#define PUPPY_EVTC_CAM_RX_IRQ		PUPPY_EVTC_L0(PUPPY_EVTC_SRC_CAM)
#define PUPPY_EVTC_CAM_TX_IRQ		PUPPY_EVTC_L1(PUPPY_EVTC_SRC_CAM)
/* FILTER */
#define PUPPY_EVTC_FILTER_EOT_IRQ	PUPPY_EVTC_L0(PUPPY_EVTC_SRC_FILTER)
#define PUPPY_EVTC_FILTER_ACT_IRQ	PUPPY_EVTC_L1(PUPPY_EVTC_SRC_FILTER)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_PUPPY_V2_EVTC_H_ */
